### ISSUE TITLE
An 'abs' missing within a 'sqrt'

### ISSUE THREAD

**Issue by fionac44** [dhaine/episensr#1]
Hi 
I have been using the package (thank you!) and I noticed that the function probsens.conf throws up an error when I use the triangular distribution for the values of p0:
probsens.conf(matrix(c(105, 85, 527, 93),
                     dimnames = list(c("HIV+", "HIV-"), c("Circ+", "Circ-")), nrow = 2, byrow = TRUE),
              reps = 20000,
              prev.exp = list("triangular", c(.7, .9, .8)),
              prev.nexp = list("triangular", c(.03, .05, .04)),
              risk = list("triangular", c(.6, .7, .65)),
              corr.p = .8)
I tracked down a likely source of error, namely a missing 'abs' inside a sqrt: 

       if (prev.nexp[[1]] == "triangular") {
            draws[, 2] <- (corr.draws[, 5] * (prev.nexp[[2]][2] - 
                prev.nexp[[2]][1]) + (prev.nexp[[2]][1] + prev.nexp[[2]][3]))/2
            draws[, 2] <- ifelse(draws[, 2] < prev.nexp[[2]][3], 
                prev.nexp[[2]][1] + sqrt(abs((prev.nexp[[2]][3] - 
                  prev.nexp[[2]][1]) * (2 * draws[, 2] - prev.nexp[[2]][1] - 
                  prev.nexp[[2]][3]))), draws[, 2])
            draws[, 2] <- ifelse(draws[, 2] > prev.nexp[[2]][3], 
                prev.nexp[[2]][2] - sqrt(2 * (prev.nexp[[2]][2] - 
                  prev.nexp[[2]][3]) * (draws[, 2] - prev.nexp[[2]][3])), 
                draws[, 2])

Thanks
Fiona

**Comment by dhaine** [comment]
Thanks @fionac44 for submitting a bug report!
I can confirm the bug and I'm working on it. We'll get back to you shortly.

**Comment by dhaine** [comment]
Bug fixed. @fionac44 you can use the development version until it is submitted to CRAN
